//! GENERATOR (bless-style) for `src/pdf/font_metrics/tables.rs` — the Core-14
//! AFM advance-width tables used for base-14 text alignment (FABLE_REVIEW
//! §3.10 / P4.HF16). Ignored by default; run on demand to regenerate:
//!
//!   node scripts/cargo-test.mjs --test gen_font_metrics -- --ignored --nocapture
//!
//! Widths are sourced from the **bundled PDFium** (its Foxit Core-14
//! substitutes are metric-compatible with Adobe's AFMs — verified: Helvetica
//! 'A'=667, 'W'=944, 'i'=222, 'm'=833, '0'=556). No network, no new deps.
//! Each glyph's advance is measured as `width("A" + c + "A") − width("AA")`,
//! which is robust for zero-ink glyphs (space) and side-bearing-heavy ones.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::fmt::Write as _;

use pdfium_render::prelude::*;
use vibepdf_lib::pdf::document::pdfium;

/// WinAnsiEncoding byte → the Unicode scalar to measure. Inverse of
/// `cos::winansi_byte`; `None` for the undefined WinAnsi slots.
fn winansi_char(byte: u8) -> Option<char> {
    let special = match byte {
        0x80 => '\u{20AC}',
        0x82 => '\u{201A}',
        0x83 => '\u{0192}',
        0x84 => '\u{201E}',
        0x85 => '\u{2026}',
        0x86 => '\u{2020}',
        0x87 => '\u{2021}',
        0x88 => '\u{02C6}',
        0x89 => '\u{2030}',
        0x8A => '\u{0160}',
        0x8B => '\u{2039}',
        0x8C => '\u{0152}',
        0x8E => '\u{017D}',
        0x91 => '\u{2018}',
        0x92 => '\u{2019}',
        0x93 => '\u{201C}',
        0x94 => '\u{201D}',
        0x95 => '\u{2022}',
        0x96 => '\u{2013}',
        0x97 => '\u{2014}',
        0x98 => '\u{02DC}',
        0x99 => '\u{2122}',
        0x9A => '\u{0161}',
        0x9B => '\u{203A}',
        0x9C => '\u{0153}',
        0x9E => '\u{017E}',
        0x9F => '\u{0178}',
        0x20..=0x7E | 0xA0..=0xFF => byte as char,
        _ => return None,
    };
    Some(special)
}

const FONTS: &[(PdfFontBuiltin, &str)] = &[
    (PdfFontBuiltin::Helvetica, "HELVETICA"),
    (PdfFontBuiltin::HelveticaBold, "HELVETICA_BOLD"),
    (PdfFontBuiltin::HelveticaOblique, "HELVETICA_OBLIQUE"),
    (PdfFontBuiltin::HelveticaBoldOblique, "HELVETICA_BOLD_OBLIQUE"),
    (PdfFontBuiltin::TimesRoman, "TIMES_ROMAN"),
    (PdfFontBuiltin::TimesBold, "TIMES_BOLD"),
    (PdfFontBuiltin::TimesItalic, "TIMES_ITALIC"),
    (PdfFontBuiltin::TimesBoldItalic, "TIMES_BOLD_ITALIC"),
];

#[test]
#[ignore = "regenerates src/pdf/font_metrics/tables.rs; run on demand"]
fn generate_font_metrics_tables() {
    let pdfium = pdfium().expect("pdfium");
    let mut doc = pdfium.create_new_pdf().expect("new pdf");

    let mut out = String::new();
    out.push_str(
        "// GENERATED by tests/gen_font_metrics.rs — do not edit by hand.\n\
         // Core-14 advance widths (/1000 em), indexed by WinAnsiEncoding byte,\n\
         // measured from bundled PDFium (== Adobe AFM). Regenerate with:\n\
         //   node scripts/cargo-test.mjs --test gen_font_metrics -- --ignored\n\
         // See FABLE_REVIEW §3.10 (P4.HF16).\n\n",
    );

    for (builtin, name) in FONTS {
        let token = doc.fonts_mut().new_built_in(*builtin);
        let size = PdfPoints::new(1000.0);
        let width = |s: &str| -> f32 {
            let obj = PdfPageTextObject::new(&doc, s, token, size).expect("text object");
            let b = obj.bounds().expect("bounds");
            (b.right() - b.left()).value
        };
        let base = width("AA");

        let mut table = [0u16; 256];
        for byte in 0u16..=255 {
            if let Some(ch) = winansi_char(byte as u8) {
                let advance = width(&format!("A{ch}A")) - base;
                #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
                {
                    table[byte as usize] = advance.round().max(0.0) as u16;
                }
            }
        }

        // Sanity: Helvetica 'A' must be 667 (guards against a silent regression).
        if *name == "HELVETICA" {
            assert_eq!(table[b'A' as usize], 667, "Helvetica 'A' should be 667");
        }

        writeln!(out, "pub(super) const {name}: [u16; 256] = [").unwrap();
        for row in table.chunks(16) {
            out.push_str("    ");
            for w in row {
                write!(out, "{w}, ").unwrap();
            }
            out.push('\n');
        }
        out.push_str("];\n\n");
    }

    let dest = std::path::Path::new("src/pdf/font_metrics/tables.rs");
    std::fs::create_dir_all(dest.parent().unwrap()).expect("mkdir");
    std::fs::write(dest, out).expect("write tables.rs");
    eprintln!("wrote {}", dest.display());
}
